### ISSUE TITLE
License.md shows 2014 as date

### ISSUE THREAD

**Issue by mikkoh** [mattdesl/module-generator#2]
Currently the generated mit license file is for 2014. Would it be handy to just drop it and use the github generated license files? This will also make it so you don't have to use all the other license types that are out there.

**Comment by mattdesl** [comment]
Fixed the date. Would be good to make this less tied to a particular license but probably falls in the scope of a rewrite. Could add a flag or something in the meantime? 

Creating repos with the GitHub site is pretty manual and tedious; and if you let it generate a readme/license it means you can't push your existing local code immediately. Instead Tom and I have been using a [shell script](https://gist.github.com/mattdesl/ccea6273c628988ff3a2) which pushes your module by name to GitHub. This also has room to do things like add a description to the repo based on package.json.

Once [this](https://github.com/node-gh/gh/issues/339) is fixed we could look into making the script into an npm tool to push new repos to GitHub.
