### ISSUE TITLE
External template support

### ISSUE THREAD

**Issue by desmondmorris** [mattdesl/module-generator#3]
Would be cool if you could pass a directory location or repo as a template source:

`module-generator -s /template` (s for source)
OR
`module-generator -s git@github.com:user/template.git`.

May be useful to set default some default paths or aliases in a rc file

``` bash
# .module-generatorrc
default=/template
es6=git@github.com:user/es6-template.git
```

Then you could do something like `module-generator es6`

**Comment by mattdesl** [comment]
:+1: 

Sounds like this:
https://github.com/mafintosh/create-project

These changes would probably turn this module into a different beast. I've got some running thoughts on a module-centric scaffolding tool:
https://github.com/mattdesl/ideas/issues/1

**Comment by desmondmorris** [comment]
+1 @mattdesl
